name: Make release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release-for-github:
    name: "Release for GitHub"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build release with Gradle
        run: ./gradlew assembleRelease

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION_TAG=$(basename $GITHUB_REF)" >> $GITHUB_ENV

      - name: Sign APKs
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Copy build artifacts
        run: |
          set -euo pipefail
          apks=("universal" "arm64-v8a" "armeabi-v7a" "x86" "x86_64")
          for abi in "${apks[@]}"; do
            src="app/build/outputs/apk/release/app-${abi}-release-signed.apk"
            dst="mpvEx-${abi}-${VERSION_TAG}.apk"
            if [ ! -f "$src" ]; then
              echo "::error file=$src::Signed APK for $abi was not found"
              exit 1
            fi
            cp "$src" "$dst"
            checksum=$(sha256sum "$dst" | awk '{ print $1 }')
            varname="apk_${abi//-/_}_sha256"
            echo "$varname=$checksum" >> "$GITHUB_ENV"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: mpvEx ${{ env.VERSION_TAG }}
          body: |
            ---
            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | arm64-v8a | ${{ env.apk_arm64_v8a_sha256 }} |
            | armeabi-v7a | ${{ env.apk_armeabi_v7a_sha256 }} |
            | Universal | ${{ env.apk_universal_sha256 }} |
            | x86 | ${{ env.apk_x86_sha256 }} |
            | x86_64 | ${{ env.apk_x86_64_sha256 }} |
          files: |
            mpvEx-universal-${{ env.VERSION_TAG }}.apk
            mpvEx-arm64-v8a-${{ env.VERSION_TAG }}.apk
            mpvEx-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            mpvEx-x86-${{ env.VERSION_TAG }}.apk
            mpvEx-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
